/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/reset-password-success'
      | '/auth/sign-in'
      | '/auth/verify-otp'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password-success': RouteRecordInfo<
      '/auth/reset-password-success',
      '/auth/reset-password-success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verify-otp': RouteRecordInfo<
      '/auth/verify-otp',
      '/auth/verify-otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tabs/overview-content': RouteRecordInfo<
      '/dashboard/tabs/overview-content',
      '/dashboard/tabs/overview-content',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tabs/report-overview': RouteRecordInfo<
      '/dashboard/tabs/report-overview',
      '/dashboard/tabs/report-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tabs/room-overview': RouteRecordInfo<
      '/dashboard/tabs/room-overview',
      '/dashboard/tabs/room-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tabs/subscription-overview': RouteRecordInfo<
      '/dashboard/tabs/subscription-overview',
      '/dashboard/tabs/subscription-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tabs/user-overview': RouteRecordInfo<
      '/dashboard/tabs/user-overview',
      '/dashboard/tabs/user-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help-center': RouteRecordInfo<
      '/help-center',
      '/help-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log/': RouteRecordInfo<
      '/log/',
      '/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manager/': RouteRecordInfo<
      '/manager/',
      '/manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manager/tabs/manager-accounts': RouteRecordInfo<
      '/manager/tabs/manager-accounts',
      '/manager/tabs/manager-accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manager/tabs/password-reset-requests': RouteRecordInfo<
      '/manager/tabs/password-reset-requests',
      '/manager/tabs/password-reset-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/report/': RouteRecordInfo<
      '/report/',
      '/report',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rooms/': RouteRecordInfo<
      '/rooms/',
      '/rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscriptions/': RouteRecordInfo<
      '/subscriptions/',
      '/subscriptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscriptions/tabs/subscription-orders-tab': RouteRecordInfo<
      '/subscriptions/tabs/subscription-orders-tab',
      '/subscriptions/tabs/subscription-orders-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscriptions/tabs/subscription-pricing-tab': RouteRecordInfo<
      '/subscriptions/tabs/subscription-pricing-tab',
      '/subscriptions/tabs/subscription-pricing-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subscriptions/tabs/user-subscriptions-tab': RouteRecordInfo<
      '/subscriptions/tabs/user-subscriptions-tab',
      '/subscriptions/tabs/user-subscriptions-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/reset-password-success'
        | '/auth/sign-in'
        | '/auth/verify-otp'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/reset-password-success.vue': {
      routes:
        | '/auth/reset-password-success'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/verify-otp.vue': {
      routes:
        | '/auth/verify-otp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tabs/overview-content.vue': {
      routes:
        | '/dashboard/tabs/overview-content'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tabs/report-overview.vue': {
      routes:
        | '/dashboard/tabs/report-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tabs/room-overview.vue': {
      routes:
        | '/dashboard/tabs/room-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tabs/subscription-overview.vue': {
      routes:
        | '/dashboard/tabs/subscription-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tabs/user-overview.vue': {
      routes:
        | '/dashboard/tabs/user-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/help-center.vue': {
      routes:
        | '/help-center'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/log/index.vue': {
      routes:
        | '/log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/manager/index.vue': {
      routes:
        | '/manager/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/manager/tabs/manager-accounts.vue': {
      routes:
        | '/manager/tabs/manager-accounts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/manager/tabs/password-reset-requests.vue': {
      routes:
        | '/manager/tabs/password-reset-requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/report/index.vue': {
      routes:
        | '/report/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/rooms/index.vue': {
      routes:
        | '/rooms/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subscriptions/index.vue': {
      routes:
        | '/subscriptions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subscriptions/tabs/subscription-orders-tab.vue': {
      routes:
        | '/subscriptions/tabs/subscription-orders-tab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subscriptions/tabs/subscription-pricing-tab.vue': {
      routes:
        | '/subscriptions/tabs/subscription-pricing-tab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subscriptions/tabs/user-subscriptions-tab.vue': {
      routes:
        | '/subscriptions/tabs/user-subscriptions-tab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
