version: '3.8'

services:
  synkork:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synkork-container
    restart: always
    ports:
      - "80:8080"
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_PORTAL_URL: ${ADMIN_PORTAL_URL}
      SERVER_URL: ${SERVER_URL}

      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALENDAR_REDIRECT_URI: ${GOOGLE_CALENDAR_REDIRECT_URI}

      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      ZEGO_APPID: ${ZEGO_APPID}
      ZEGO_SERVER_SECRET: ${ZEGO_SERVER_SECRET}

      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL}

      MOMO_ACCESS_KEY: ${MOMO_ACCESS_KEY}
      MOMO_SECRET_KEY: ${MOMO_SECRET_KEY}