package com.synkork.backend.modules.admin.auditLog.enums;

public enum LogActionEnum {
    CREATE_USER,
    CREATE_INVOICE,
    UPDATE_INVOICE,
    DELETE_INVOICE,
    CANCEL_SUBSCRIPTION,
    UPDATE_SUBSCRIPTION,

    BAN_USER,
    UNBAN_USER,
    WARN_USER,
    UPDATE_USER,
    DELETE_USER,

    CREATE_WORKSPACE,
    UPDATE_WORKSPACE,
    DELETE_WORKSPACE,
    LOCK_WORKSPACE,
    UNLOCK_WORKSPACE,
    WARN_WORKSPACE,

    CREATE_MANAGER,
    UPDATE_MANAGER,
    LOCK_MANAGER,

    RESOLVE_REPORT,
    DISMISS_REPORT,
    REPORT_CREATED,
    REPORT_REVIEWED,
    REPORT_DELETED
}
