spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/synkork?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

    encoding:
      charset: UTF-8
      enabled: true
      force: true

  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:}

nvidia:
  api-key: ${NVIDIA_API_KEY:}
  base-url: ${NVIDIA_BASE_URL:https://integrate.api.nvidia.com/v1}

momo:
  partner-code: MOMO
  access-key: ${MOMO_ACCESS_KEY:}
  secret-key: ${MOMO_SECRET_KEY:}
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: ${FRONTEND_URL:}/me/subscriptions
  ipn-url: ${SERVER_URL:}/api/payment/momo/callback

server:
  port: 8080
  servlet:
    context-path: /api

frontend:
  client:
    url: ${FRONTEND_URL:http://localhost:5173}
  admin:
    url: ${ADMIN_PORTAL_URL:http://localhost:5174}

jwt:
  secret: CFGSc60ez6n093BbLoqk1BdPFa02l26UBAjKvFGAw3Q

gmail:
  username: ${GMAIL_USERNAME:}
  password: ${GMAIL_PASSWORD:}

cloudinary:
  name: ${CLOUDINARY_CLOUD_NAME:}
  key: ${CLOUDINARY_API_KEY:}
  secret: ${CLOUDINARY_API_SECRET:}

zego:
  appId: ${ZEGO_APPID}
  secret: ${ZEGO_SERVER_SECRET}

google:
  calendar:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_CALENDAR_REDIRECT_URI}
